# Generated by Django 6.0.1 on 2026-01-23 13:37

import tienda_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(blank=True, default='default/default.png', null=True, upload_to=tienda_app.models.imagen_upload_to, verbose_name='Avatar')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.IntegerField(null=True)),
                ('categoria', models.CharField(max_length=30)),
                ('fecha_de_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
